spring.application.name=workout-gen-svc
server.port=8081

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/workout_gen_svc
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

logging.level.org=WARN
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor=DEBUG
logging.level.com.workoutgensvc.core.AIService=DEBUG

openai.api.model=gpt-3.5-turbo
chat2api.base-url=http://localhost:5005
chat2api.access-token=

chat2api.path=chat2api
chat2api.command.start=start-chat2api
chat2api.command.setup=setup-chat2api